### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by hackel** [MinnPost/minnpost-minimum-wage-timeline#1]
The link to

https://spreadsheets.google.com/feeds/list/0AjYft7IGrHzNdFZTV0tHRGtEVWxrQXhRUGJ3emtoZmc/csv/public/values?sq=&alt=json

returns `Invalid query parameter value for grid_id.`, causing the whole timeline to break.

**Comment by tnehil** [comment]
Hey,

Thanks for pointing this out. I updated the spreadsheet key in 8256f252d4754b7c0ddbfa4be473d5f9afdbd879 and everything appears to be working now.
